/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-surface': '#e2e2e2',
        'on-error-container': '#ffdad6',
        tertiary: '#ffffff',
        'surface-variant': '#353535',
        'secondary-fixed': '#d8e2ff',
        'on-secondary-fixed': '#001a43',
        'on-background': '#e2e2e2',
        error: '#ffb4ab',
        'tertiary-container': '#efdbff',
        'surface-tint': '#c6c6c7',
        'primary-fixed': '#e2e2e2',
        'on-primary-container': '#636565',
        'secondary-fixed-dim': '#aec6ff',
        'primary-container': '#e2e2e2',
        'surface-bright': '#393939',
        'on-secondary-container': '#00275e',
        'on-primary-fixed-variant': '#454747',
        'on-tertiary-container': '#8638d7',
        'surface-container': '#1f1f1f',
        'on-tertiary-fixed-variant': '#6600b7',
        'on-secondary-fixed-variant': '#004397',
        'on-primary-fixed': '#1a1c1c',
        'secondary-container': '#508eff',
        background: '#111111',
        'surface-container-highest': '#353535',
        'on-tertiary': '#470083',
        'surface-dim': '#111111',
        'inverse-surface': '#e2e2e2',
        'tertiary-fixed': '#efdbff',
        'on-error': '#690005',
        'surface-container-low': '#1a1a1a',
        'on-primary': '#2f3131',
        'surface-container-high': '#151515',
        'primary-fixed-dim': '#c6c6c7',
        surface: '#111111',
        'on-secondary': '#002e6b',
        primary: '#ffffff',
        'inverse-primary': '#5d5f5f',
        'inverse-on-surface': '#303030',
        'tertiary-fixed-dim': '#dbb8ff',
        'outline-variant': '#222222',
        secondary: '#aec6ff',
        'on-surface-variant': '#c4c7c8',
        'surface-container-lowest': '#0a0a0a',
        outline: '#444444',
        'error-container': '#93000a',
        'on-tertiary-fixed': '#2b0052',
      },
      fontFamily: {
        headline: ['Geist', 'Inter', 'sans-serif'],
        body: ['Geist', 'Inter', 'sans-serif'],
        label: ['Geist Mono', 'Space Grotesk', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
